behaviors:
  CarAgent:
    trainer_type: ppo

    hyperparameters:
      batch_size: 1024
      buffer_size: 20480
      learning_rate: 0.0005
      beta: 0.02
      epsilon: 1.0
      lambd: 0.95
      num_epoch: 7

    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 3

    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        strength: 0.05
        gamma: 0.99
        encoding_size: 256

    max_steps: 50000000
    time_horizon: 256
    summary_freq: 25000
    checkpoint_interval: 1000000
