behaviors:
  CarAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 20480
      learning_rate: 0.0005
      beta: 0.02
      epsilon: 1.0
      lambd: 0.95
      num_epoch: 3
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 3
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        strength: 0.05
        gamma: 0.99
        encoding_size: 256

      gail:
        strength: 0.01
        gamma: 0.99
        encoding_size: 128
        demo_path: "C:\\Users\\UTENTE\\git\\smart-car\\smart-car\\Assets\\Demonstrations\\drivingdemodemo.demo"
        learning_rate: 3.0e-4
        use_actions: false
        use_vail: false

    max_steps: 30000000
    time_horizon: 256
    summary_freq: 5000
    checkpoint_interval: 50000
