behaviors:
  CarAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 102400
      learning_rate: 0.0003
      beta: 0.02
      epsilon: 0.25
      lambd: 0.95
      num_epoch: 3
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 3
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        strength: 0.01
        gamma: 0.99
        encoding_size: 128
    max_steps: 30000000
    time_horizon: 256
    summary_freq: 5000
    checkpoint_interval: 50000
