behaviors:
  CarAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.1
      lambd: 0.95
      num_epoch: 7
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 3
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        strength: 0.05
        gamma: 0.99

      gail:
        strength: 0.1
        gamma: 0.99
        demo_path: "C:\\Users\\UTENTE\\git\\smart-car\\smart-car\\Assets\\Demonstrations\\medium-stacked-1.demo"
        learning_rate: 3.0e-4
        use_actions: true
        use_vail: false

    max_steps: 50000000
    time_horizon: 256
    summary_freq: 25000
    checkpoint_interval: 500000
